import { Hero } from '@/components'
import { Metadata } from 'next'
import styles from './page.module.css'

export const metadata: Metadata = {
  title: 'Title',
  description: 'Generated by create next app 2',
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true },
  },
}

export default async function Home() {
  return (
    <div className={styles.main}>
      <Hero />
    </div>
  )
}
