import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Short link',
  description: 'Generated by create next app 2',
}

export default async function Link() {
  return <div>Link</div>
}
